### ISSUE TITLE
Releasing rqt_action to crystal

### ISSUE THREAD

**Issue by mlautman** [ros-visualization/rqt_action#5]
@dirk-thomas This should be ready for release. If you invite me to collaborate on the release repo I can take care of getting that out.

**Comment by dirk-thomas** [comment]
I sent you an invite for the ROS 2 release repo: https://github.com/ros2-gbp/rqt_action-release

Thanks for taking care of the release.

**Comment by clalancette** [comment]
This looks to be available in all of the current ROS 2 distributions, so I'm going to close this out.
